sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile ..."
  - docker build -t kendrick0929/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kendrick0929/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-016250937053"
  bucket_path: "elasticbeanstalk-ap-northeast-2-016250937053"
  on:
    branch: master

  access_key_id: $AWS-ACCESS-KEY
  secre_access_key: $AWS-SECRET-KEY
