sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile ..."
  - docker build -t kendrick0929/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kendrick0929/docker-react npm run test -- --coverage

after_success:
  - echo "Test success !"